--------------------------------------------------------
--  File created - Saturday-November-08-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table METADATA_ATTRIBUTES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."METADATA_ATTRIBUTES" 
   (	"METADATA_ID" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_NAME" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_ALIAS" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_NO" NUMBER(3,0), 
	"ATTRIBUTE_DEFINITION" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE_TYPE" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_WIDTH" NUMBER(4,0), 
	"ATTRIBUTE_PRECISION" NUMBER(2,0), 
	"ATTRIBUTE_SCALE" NUMBER(2,0), 
	"CODESET_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Table METADATA_CITATIONS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."METADATA_CITATIONS" 
   (	"CITATION_ID" VARCHAR2(30 BYTE), 
	"CITATION_TITLE" VARCHAR2(255 BYTE), 
	"CITATION_ORIGINATOR" VARCHAR2(255 BYTE), 
	"CITATION_PUBDATE" VARCHAR2(30 BYTE), 
	"CITATION_EDITION" VARCHAR2(30 BYTE), 
	"CITATION_DATA_FORM" VARCHAR2(30 BYTE), 
	"CITATION_SERIES" VARCHAR2(255 BYTE), 
	"ISSUE_IDENTIFICATION" VARCHAR2(255 BYTE), 
	"PUBLICATION_PLACE" VARCHAR2(30 BYTE), 
	"PUBLISHER" VARCHAR2(255 BYTE), 
	"ONLINE_LINKAGE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Table METADATA_GROUPS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."METADATA_GROUPS" 
   (	"GROUP_ID" VARCHAR2(30 BYTE), 
	"USE_CONSTRAINT" VARCHAR2(4000 BYTE), 
	"ACCESS_CONSTRAINT" VARCHAR2(30 BYTE), 
	"PURPOSE" VARCHAR2(4000 BYTE), 
	"CONTACT_ID" NUMBER, 
	"METADATA_CONTACT_ID" NUMBER, 
	"ATTRIBUTE_ACCURACY_REPORT" VARCHAR2(4000 BYTE), 
	"THUMBNAIL" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Table METADATA_KEYWORDS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."METADATA_KEYWORDS" 
   (	"METADATA_ID" VARCHAR2(30 BYTE), 
	"KEYWORD_TYPE" VARCHAR2(12 BYTE), 
	"KEYWORD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Table METADATA_MAIN
--------------------------------------------------------

  CREATE TABLE "ADMIN"."METADATA_MAIN" 
   (	"METADATA_ID" VARCHAR2(30 BYTE), 
	"GROUP_ID" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(255 BYTE), 
	"ABSTRACT" VARCHAR2(4000 BYTE), 
	"SUPPLEMENTAL_INFORMATION" VARCHAR2(255 BYTE), 
	"CITATION_ID" VARCHAR2(30 BYTE), 
	"PUBLICATION_DATE" VARCHAR2(30 BYTE), 
	"STATUS_PROGRESS" VARCHAR2(30 BYTE), 
	"UPDATE_FREQUENCY" VARCHAR2(30 BYTE), 
	"SECURITY_CLASSIFICATION" VARCHAR2(30 BYTE), 
	"WEST_BOUNDING_COORDINATE" NUMBER(9,6), 
	"EAST_BOUNDING_COORDINATE" NUMBER(9,6), 
	"NORTH_BOUNDING_COORDINATE" NUMBER(9,6), 
	"SOUTH_BOUNDING_COORDINATE" NUMBER(9,6), 
	"TEMPORAL_DATE_FROM" DATE, 
	"TEMPORAL_DATE_TO" DATE, 
	"METADATA_FACING" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
  GRANT SELECT ON "ADMIN"."METADATA_MAIN" TO "LANDIS";
--------------------------------------------------------
--  DDL for Table METADATA_MAIN_SOURCE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."METADATA_MAIN_SOURCE" 
   (	"ID" NUMBER, 
	"METADATA_ID" VARCHAR2(30 BYTE), 
	"SOURCE_ID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Table METADATA_SOURCE_CITATION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."METADATA_SOURCE_CITATION" 
   (	"SOURCE_ID" VARCHAR2(4 BYTE), 
	"CITATION_ID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Table METADATA_SOURCES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."METADATA_SOURCES" 
   (	"SOURCE_ID" VARCHAR2(4 BYTE), 
	"SOURCE_NAME" VARCHAR2(255 BYTE), 
	"SOURCE_SCALE" VARCHAR2(30 BYTE), 
	"SOURCE_MEDIA" VARCHAR2(30 BYTE), 
	"SOURCE_CONTRIBUTION" VARCHAR2(255 BYTE), 
	"CITATION_ID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Index METADATA_ATTRIBUTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."METADATA_ATTRIBUTES_PK" ON "ADMIN"."METADATA_ATTRIBUTES" ("METADATA_ID", "ATTRIBUTE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Index METADATA_CITATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."METADATA_CITATIONS_PK" ON "ADMIN"."METADATA_CITATIONS" ("CITATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Index METADATA_GROUPS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."METADATA_GROUPS_PK" ON "ADMIN"."METADATA_GROUPS" ("GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Index METADATA_MAIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."METADATA_MAIN_PK" ON "ADMIN"."METADATA_MAIN" ("METADATA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Index METADATA_MAIN_SOURCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."METADATA_MAIN_SOURCE_PK" ON "ADMIN"."METADATA_MAIN_SOURCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Index METADATA_SOURCES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."METADATA_SOURCES_PK" ON "ADMIN"."METADATA_SOURCES" ("SOURCE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Trigger bi_METADATA_MAIN_SOURCE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."bi_METADATA_MAIN_SOURCE" 
  before insert on "METADATA_MAIN_SOURCE"              
  for each row 
begin  
  for c1 in ( 
    select "METADATA_MAIN_SOURCE_SEQ".nextval next_val 
    from dual 
  ) loop 
    :new."ID" :=  c1.next_val; 
  end loop; 
end;




/
ALTER TRIGGER "ADMIN"."bi_METADATA_MAIN_SOURCE" ENABLE;
BEGIN 
  DBMS_DDL.SET_TRIGGER_FIRING_PROPERTY('"ADMIN"','"bi_METADATA_MAIN_SOURCE"',FALSE) ; 
END;

/
--------------------------------------------------------
--  Constraints for Table METADATA_ATTRIBUTES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."METADATA_ATTRIBUTES" ADD CONSTRAINT "METADATA_ATTRIBUTES_PK" PRIMARY KEY ("METADATA_ID", "ATTRIBUTE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN"  ENABLE;
--------------------------------------------------------
--  Constraints for Table METADATA_CITATIONS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."METADATA_CITATIONS" ADD CONSTRAINT "METADATA_CITATIONS_PK" PRIMARY KEY ("CITATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN"  ENABLE;
--------------------------------------------------------
--  Constraints for Table METADATA_GROUPS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."METADATA_GROUPS" ADD CONSTRAINT "METADATA_GROUPS_PK" PRIMARY KEY ("GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN"  ENABLE;
--------------------------------------------------------
--  Constraints for Table METADATA_KEYWORDS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."METADATA_KEYWORDS" MODIFY ("METADATA_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."METADATA_KEYWORDS" MODIFY ("KEYWORD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."METADATA_KEYWORDS" MODIFY ("KEYWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table METADATA_MAIN
--------------------------------------------------------

  ALTER TABLE "ADMIN"."METADATA_MAIN" ADD CONSTRAINT "METADATA_MAIN_PK" PRIMARY KEY ("METADATA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN"  ENABLE;
--------------------------------------------------------
--  Constraints for Table METADATA_MAIN_SOURCE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."METADATA_MAIN_SOURCE" ADD CONSTRAINT "METADATA_MAIN_SOURCE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN"  ENABLE;
--------------------------------------------------------
--  Constraints for Table METADATA_SOURCES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."METADATA_SOURCES" ADD CONSTRAINT "METADATA_SOURCES_PK" PRIMARY KEY ("SOURCE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table METADATA_ATTRIBUTES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."METADATA_ATTRIBUTES" ADD CONSTRAINT "METADATA_ATTRIBUTES_FK" FOREIGN KEY ("METADATA_ID")
	  REFERENCES "ADMIN"."METADATA_MAIN" ("METADATA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table METADATA_KEYWORDS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."METADATA_KEYWORDS" ADD CONSTRAINT "FK_MD_KEYWORDS" FOREIGN KEY ("METADATA_ID")
	  REFERENCES "ADMIN"."METADATA_MAIN" ("METADATA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table METADATA_SOURCE_CITATION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."METADATA_SOURCE_CITATION" ADD CONSTRAINT "MAIN_CITATION_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "ADMIN"."METADATA_SOURCES" ("SOURCE_ID") ENABLE;
  ALTER TABLE "ADMIN"."METADATA_SOURCE_CITATION" ADD CONSTRAINT "MAIN_CITATION_CITATION_FK" FOREIGN KEY ("CITATION_ID")
	  REFERENCES "ADMIN"."METADATA_CITATIONS" ("CITATION_ID") ENABLE;
